### ISSUE TITLE
Multiples and [videoID]

### ISSUE THREAD

**Issue by kalicki** [ZouYouShun/ngx-y2-player#3]
Hey

I have a situation where I have several videos, not to load all I made a solution based on slides (prev, current, next) with this I only load 3 elements the (prev and next) are loaded for bufferization. Your solution helped me a lot, but it is not very nice to multiples iframes. I suggest to create a tag called  `[videoID]="..."` that from the change of this element it updates with new video and the  `[playerOptions]="..."` is isolated to the settings.

Actually: 
```
<div class="video-prev" #videoPrev>
      <ngx-y2-player #recipeVideo1 class="video-player" [playerOptions]="playerOptions1" [container]="videoPrev"
        [@shift]="videoState1" (ready)="onReady($event)">
      </ngx-y2-player>
    </div>

    <div class="video-current" #videoCurrent>
      <ngx-y2-player #recipeVideo2 class="video-player" [playerOptions]="playerOptions2" [container]="videoCurrent"
        [@shift]="videoState2" (ready)="onReady($event)">
      </ngx-y2-player>
    </div>

    <div class="video-next" #videoNext>
      <ngx-y2-player #recipeVideo3 class="video-player" [playerOptions]="playerOptions3" [container]="videoNext"
        [@shift]="videoState3" (ready)="onReady($event)">
      </ngx-y2-player>
    </div>
```

Idea
```
<ngx-y2-player [playerOptions]="playerOptions" [videoID]="LOREMIPSUM">
      </ngx-y2-player>

or (based array of elements)

<ngx-y2-player [playerOptions]="playerOptions" [videoID]="[url1, url2, url3]">
      </ngx-y2-player>
```

**Comment by ZouYouShun** [comment]
Hi @kalicki, thanks for your suggestion.

In current state, you can use [youtube API](https://developers.google.com/youtube/iframe_api_reference) to change current video,

Here is the example with change video and play list.
https://stackblitz.com/edit/ngx-y2-player-example
***(in the stackblitz, we should reload the preview page manual, otherwise the youtube api will load fail.)***

When I create this repository, I don't put too much controller with angular live cycle, because the youtube api offer many method to control player, I prefer to using that api directly.

But I thinks I will change the videoId to independent [input], let id change more easy.

**Comment by ZouYouShun** [comment]
I add [videoId] with 2.0.0 

more detial in https://alanzouhome.firebaseapp.com/package/NgxY2Player

https://github.com/ZouYouShun/ngx-y2-player/blob/master/CHANGELOG..md

**Comment by kalicki** [comment]
100% works!
